/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "_6a7vOp7Nm0",
    title: "Bread Pizza Sandwich",
    description:
      "Pizza is liked by every one whether it be a smaller one in house or the elder ones. But making pizza is a cumbersome process and it takes a lot of time and patience. That is the reason  most of the time, we do not bake pizza at home and just order it from outside. ",
    creator: "INDIA Eats",
    categoryName: "Italian",
    timeDuration: "5min",
    url: "hdioNWyv86k",
    views: "10 views",
    likes: "532k likes",
    uploaded: "Feb 26, 2018",
    imgUrl: "https://i3.ytimg.com/vi/hdioNWyv86k/maxresdefault.jpg",
    isMustWatch: true,
  },
  {
    _id: "xL6wySUJXbE",
    title: "Pasta in White Sauce ",
    description:
      "Pizza is liked by every one whether it be a smaller one in house or the elder ones. But making pizza is a cumbersome process and it takes a lot of time and patience. That is the reason  most of the time, we do not bake pizza at home and just order it from outside.",
    creator: "Flavours Of Food",
    categoryName: "Italian",
    timeDuration: "5min",
    url: "TgSkS53CrjQ",
    views: "32 views",
    likes: "616k likes",
    uploaded: "Sep 27, 2017",
    imgUrl: "https://i3.ytimg.com/vi/TgSkS53CrjQ/maxresdefault.jpg",
    isMustWatch: false,
  },
  {
    _id: "ie5NdWCXK3A",
    title: "No Oven Paneer Pizza",
    description:
      "Now make this awesomely delicious pizza without using yeast or oven at home. You can checkout our veg. pizza without oven recipe for details steps to make pizza sauce.",
    creator: "The Terrace Kitchen",
    categoryName: "Italian",
    timeDuration: "7min",
    url: "iODYdP8Z6tQ",
    views: "63 views",
    likes: "115k likes",
    uploaded: "Jan 28, 2018",
    imgUrl: "https://i3.ytimg.com/vi/iODYdP8Z6tQ/maxresdefault.jpg",
    isMustWatch: false,
  },
  {
    _id: "erXfC_hs7Ew",
    title: "Famous Chinese Chopsuey",
    description:
      "Saucy vegetables topped with crisp fried noodles, a popular recipe of Indo Chinese cuisine is Chinese Chopsuey. So with Varun learn to make Chinese Chopsuey at home only on Rajshri Food.",
    creator: "Rajshri Food",
    categoryName: "Chineese",
    timeDuration: "5min",
    url: "eePVIsvz0Xg",
    views: "19 views",
    likes: "30k likes",
    uploaded: "Jul 1, 2016",
    imgUrl: "https://i3.ytimg.com/vi/eePVIsvz0Xg/maxresdefault.jpg",
    isMustWatch: true,
  },

  {
    _id: "B_qhDw4Ps7g",
    title: "Famous Indian Street Chinese",
    description:
      "We are a food explorer from Surat City, Gujarat.  We love to eat and travel. contact us to Promote your restaurant, hotel, cafe, or any food corner on our social media platforms. ",
    creator: "Tasty Street Food",
    categoryName: "Chineese",
    timeDuration: "4min",
    url: "MDXiYHRk5s0",
    views: "13 views",
    likes: "15k likes",
    uploaded: "Oct 2, 2020",
    imgUrl: "https://i3.ytimg.com/vi/MDXiYHRk5s0/maxresdefault.jpg",
    isMustWatch: false,
  },
  {
    _id: "JOko1ygjPwk",
    title: "The Spanish Potatoes",
    description:
      "Spain on a Fork is a member of the Amazon Affiliates Program. If you purchase through these links, you pay the same price, and Spain on a Fork receives a small commission, which helps with all the expenses to keep Spain on a Fork going.",
    creator: "Spain on a Fork",
    categoryName: "Spanish",
    timeDuration: "8min",
    url: "wZ6AWwWESoA",
    views: "11 views",
    likes: "37k likes",
    uploaded: "Jun 5, 2020",
    imgUrl: "https://i3.ytimg.com/vi/wZ6AWwWESoA/maxresdefault.jpg",
    isMustWatch: true,
  },
  {
    _id: "y32sMVJ1IY4",
    title: "Ultimate Spanish Omelette",
    description:
      "Mastering a classic Spanish dish just got easier.  The wonderful Omar Allibhoy is back with his favourite recipe for Tortilla de Patatas - or Spanish omelette to you and me!",
    creator: "Jamie Oliver",
    categoryName: "Spanish",
    timeDuration: "6min",
    url: "JceGMNG7rpU",
    views: "72 views",
    likes: "111k likes",
    uploaded: "Jul 29, 2015",
    imgUrl: "https://i3.ytimg.com/vi/JceGMNG7rpU/maxresdefault.jpg",
    isMustWatch: false,
  },

  {
    _id: "N1LoztmlZ4Q",
    title: "Garlic Bread Without Oven",
    description:
      "Gralic Bread Without Oven | Cheesy Garlic Bread | Garlic Bread in Kadhai ~ The Terrace Kitchen",
    creator: "The Terrace Kitchen",
    categoryName: "Italian",
    timeDuration: "7min",
    url: "B97ExMoJ5JE",
    views: "31 views",
    likes: "61k likes",
    uploaded: "Mar 25, 2018",
    imgUrl: "https://i3.ytimg.com/vi/B97ExMoJ5JE/maxresdefault.jpg",
    isMustWatch: true,
  },

  {
    _id: "4B-njzVxO8g",
    title: "Eggless Choco Lava Cake",
    description:
      " Baking is a very crucial part of this recipe. If you overcook this cake, you will not get any lava at the center of the cake.",
    creator: "The Terrace Kitchen",
    categoryName: "Cake",
    timeDuration: "8min",
    url: "rWHHcKvkYsI",
    views: "45 views",
    likes: "107k likes",
    uploaded: "Nov 8, 2017",
    imgUrl: "https://i3.ytimg.com/vi/rWHHcKvkYsI/maxresdefault.jpg",
    isMustWatch: false,
  },
  {
    _id: "bStNpajvHcU",
    title: "Best Chocolate Cake",
    description:
      "Best Chocolate Cake Recipe, Easy Chocolate Cake Recipe, Eggless and Without Oven, Birthday Cake ",
    creator: "With Dr.Alisha",
    categoryName: "Cake",
    timeDuration: "10min",
    url: "J7bjH5IdMjc",
    views: "57 views",
    likes: "126k likes",
    uploaded: "Mar 23, 2021",
    imgUrl: "https://i3.ytimg.com/vi/J7bjH5IdMjc/maxresdefault.jpg",
    isMustWatch: true,
  },
  {
    _id: "gStnpajpHKo",
    title: "Chocolate Oreo Cake",
    description:
      "5 Minute Bread Cake With Oreo, Bread Cake Recipe, Oreo Cake Recipe, Oreo Biscuit Cake, oreo cake with 3 ingredients,  ",
    creator: "Selines Recipes",
    categoryName: "Cake",
    timeDuration: "5min",
    url: "zixzwT4ZtuQ",
    views: "76 views",
    likes: "81k likes",
    uploaded: "Oct 10, 2020",
    imgUrl: "https://i3.ytimg.com/vi/zixzwT4ZtuQ/maxresdefault.jpg",
    isMustWatch: false,
  },
  {
    _id: "qwertgbhghi",
    title: "Chocolate Truffle Cake",
    description:
      "Super Easy Chocolate Truffle Cake In kadai | No Whipping Cream, No Oven | Eggless Chocolate Cake ",
    creator: "With Dr.Alisha",
    categoryName: "Cake",
    timeDuration: "11min",
    url: "DBvEvuudpGs",
    views: "57 views",
    likes: "46k likes",
    uploaded: "Jun 19, 2021",
    imgUrl: "https://i3.ytimg.com/vi/DBvEvuudpGs/maxresdefault.jpg",
    isMustWatch: false,
  },
];
